name: iBan
main: fr.GHOSTnew.iBan.iBan
version: 1.7
author: GHOSTnew
commands:
   iban:
      description: iBan commands
      usage: /<command> <player> <raison>
permissions:
  iBan.canBan:
    description: commande iBan
    default: op